#display_color: "#194878" # blue
display_color: "#2b712b" # green

server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true


management:
  endpoints:
    web:
      exposure:
        include: "*"